// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxOYUdEdCLRlAPVPEPgcZpPC9spFo_yR8',
    appId: '1:635351984981:web:b57de993f44a52024b9ddc',
    messagingSenderId: '635351984981',
    projectId: 'closers-1a548',
    authDomain: 'closers-1a548.firebaseapp.com',
    storageBucket: 'closers-1a548.appspot.com',
    measurementId: 'G-NPQ3T0VCSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAItqajhmM7ZkO50H-Gh9rakKstip1-9ZM',
    appId: '1:635351984981:android:cf9cbfe156890bf44b9ddc',
    messagingSenderId: '635351984981',
    projectId: 'closers-1a548',
    storageBucket: 'closers-1a548.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK444yevBb7OMdvZQYd0DbhgpcUfiJ3BY',
    appId: '1:635351984981:ios:3ab44d2161996e6b4b9ddc',
    messagingSenderId: '635351984981',
    projectId: 'closers-1a548',
    storageBucket: 'closers-1a548.appspot.com',
    iosClientId: '635351984981-fh4tdfd9dlg8asujgbthc3i0dvntihla.apps.googleusercontent.com',
    iosBundleId: 'com.outfieldapp.closers.dev',
  );
}
